Dias = ("segunda", "terça", "quarta", "quinta", "sexta", "sábado", "domingo")
print(Dias)
print(Dias[0])
print(Dias[1])
print(Dias[2])
print(Dias[3])
print(Dias[4])
print(Dias[5])
print(Dias[6])
print(len(Dias))
